/*
 * This file is generated by jOOQ.
*/
package com.example.stline.db;


import com.example.stline.db.tables.Messages;
import com.example.stline.db.tables.Order;
import com.example.stline.db.tables.OrderDetails_;
import com.example.stline.db.tables.Posts;
import com.example.stline.db.tables.Product___;
import com.example.stline.db.tables.ProductsCategory_;
import com.example.stline.db.tables.ProductsMark_;
import com.example.stline.db.tables.Telegrammessages;
import com.example.stline.db.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1520522676;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.messages</code>.
     */
    public final Messages MESSAGES = com.example.stline.db.tables.Messages.MESSAGES;

    /**
     * The table <code>public.order</code>.
     */
    public final Order ORDER = com.example.stline.db.tables.Order.ORDER;

    /**
     * The table <code>public.order_details_</code>.
     */
    public final OrderDetails_ ORDER_DETAILS_ = com.example.stline.db.tables.OrderDetails_.ORDER_DETAILS_;

    /**
     * The table <code>public.posts</code>.
     */
    public final Posts POSTS = com.example.stline.db.tables.Posts.POSTS;

    /**
     * The table <code>public.product___</code>.
     */
    public final Product___ PRODUCT___ = com.example.stline.db.tables.Product___.PRODUCT___;

    /**
     * The table <code>public.products_category_</code>.
     */
    public final ProductsCategory_ PRODUCTS_CATEGORY_ = com.example.stline.db.tables.ProductsCategory_.PRODUCTS_CATEGORY_;

    /**
     * The table <code>public.products_mark_</code>.
     */
    public final ProductsMark_ PRODUCTS_MARK_ = com.example.stline.db.tables.ProductsMark_.PRODUCTS_MARK_;

    /**
     * The table <code>public.telegramMessages</code>.
     */
    public final Telegrammessages TELEGRAMMESSAGES = com.example.stline.db.tables.Telegrammessages.TELEGRAMMESSAGES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.example.stline.db.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Messages.MESSAGES,
            Order.ORDER,
            OrderDetails_.ORDER_DETAILS_,
            Posts.POSTS,
            Product___.PRODUCT___,
            ProductsCategory_.PRODUCTS_CATEGORY_,
            ProductsMark_.PRODUCTS_MARK_,
            Telegrammessages.TELEGRAMMESSAGES,
            Users.USERS);
    }
}
