/*
 * This file is generated by jOOQ.
*/
package com.example.stline.db;


import com.example.stline.db.tables.Messages;
import com.example.stline.db.tables.Order;
import com.example.stline.db.tables.OrderDetails_;
import com.example.stline.db.tables.Posts;
import com.example.stline.db.tables.Product___;
import com.example.stline.db.tables.ProductsCategory_;
import com.example.stline.db.tables.ProductsMark_;
import com.example.stline.db.tables.Telegrammessages;
import com.example.stline.db.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.messages</code>.
     */
    public static final Messages MESSAGES = com.example.stline.db.tables.Messages.MESSAGES;

    /**
     * The table <code>public.order</code>.
     */
    public static final Order ORDER = com.example.stline.db.tables.Order.ORDER;

    /**
     * The table <code>public.order_details_</code>.
     */
    public static final OrderDetails_ ORDER_DETAILS_ = com.example.stline.db.tables.OrderDetails_.ORDER_DETAILS_;

    /**
     * The table <code>public.posts</code>.
     */
    public static final Posts POSTS = com.example.stline.db.tables.Posts.POSTS;

    /**
     * The table <code>public.product___</code>.
     */
    public static final Product___ PRODUCT___ = com.example.stline.db.tables.Product___.PRODUCT___;

    /**
     * The table <code>public.products_category_</code>.
     */
    public static final ProductsCategory_ PRODUCTS_CATEGORY_ = com.example.stline.db.tables.ProductsCategory_.PRODUCTS_CATEGORY_;

    /**
     * The table <code>public.products_mark_</code>.
     */
    public static final ProductsMark_ PRODUCTS_MARK_ = com.example.stline.db.tables.ProductsMark_.PRODUCTS_MARK_;

    /**
     * The table <code>public.telegramMessages</code>.
     */
    public static final Telegrammessages TELEGRAMMESSAGES = com.example.stline.db.tables.Telegrammessages.TELEGRAMMESSAGES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = com.example.stline.db.tables.Users.USERS;
}
