/*
 * This file is generated by jOOQ.
 */
package com.example.stline.db.public_;


import com.example.stline.db.public_.tables.Messages;
import com.example.stline.db.public_.tables.Photos;
import com.example.stline.db.public_.tables.Posts;
import com.example.stline.db.public_.tables.Products;
import com.example.stline.db.public_.tables.Roles;
import com.example.stline.db.public_.tables.Users;
import com.example.stline.db.public_.tables.records.MessagesRecord;
import com.example.stline.db.public_.tables.records.PhotosRecord;
import com.example.stline.db.public_.tables.records.PostsRecord;
import com.example.stline.db.public_.tables.records.ProductsRecord;
import com.example.stline.db.public_.tables.records.RolesRecord;
import com.example.stline.db.public_.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MessagesRecord> MESSAGES_PKEY = UniqueKeys0.MESSAGES_PKEY;
    public static final UniqueKey<PhotosRecord> PHOTOS_PKEY = UniqueKeys0.PHOTOS_PKEY;
    public static final UniqueKey<PostsRecord> POSTS_PKEY = UniqueKeys0.POSTS_PKEY;
    public static final UniqueKey<ProductsRecord> PRODUCTS_PKEY = UniqueKeys0.PRODUCTS_PKEY;
    public static final UniqueKey<RolesRecord> ROLES_PKEY = UniqueKeys0.ROLES_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PhotosRecord, ProductsRecord> PHOTOS__FK_PHOTOS_PRODUCTS = ForeignKeys0.PHOTOS__FK_PHOTOS_PRODUCTS;
    public static final ForeignKey<PostsRecord, UsersRecord> POSTS__FK_POSTS_USERS = ForeignKeys0.POSTS__FK_POSTS_USERS;
    public static final ForeignKey<UsersRecord, RolesRecord> USERS__FK_USERS_ROLES = ForeignKeys0.USERS__FK_USERS_ROLES;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<MessagesRecord> MESSAGES_PKEY = Internal.createUniqueKey(Messages.MESSAGES, "messages_pkey", Messages.MESSAGES.ID);
        public static final UniqueKey<PhotosRecord> PHOTOS_PKEY = Internal.createUniqueKey(Photos.PHOTOS, "photos_pkey", Photos.PHOTOS.ID);
        public static final UniqueKey<PostsRecord> POSTS_PKEY = Internal.createUniqueKey(Posts.POSTS, "posts_pkey", Posts.POSTS.ID);
        public static final UniqueKey<ProductsRecord> PRODUCTS_PKEY = Internal.createUniqueKey(Products.PRODUCTS, "products_pkey", Products.PRODUCTS.ID);
        public static final UniqueKey<RolesRecord> ROLES_PKEY = Internal.createUniqueKey(Roles.ROLES, "roles_pkey", Roles.ROLES.ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<PhotosRecord, ProductsRecord> PHOTOS__FK_PHOTOS_PRODUCTS = Internal.createForeignKey(com.example.stline.db.public_.Keys.PRODUCTS_PKEY, Photos.PHOTOS, "photos__fk_photos_products", Photos.PHOTOS.PRODUCT);
        public static final ForeignKey<PostsRecord, UsersRecord> POSTS__FK_POSTS_USERS = Internal.createForeignKey(com.example.stline.db.public_.Keys.USERS_PKEY, Posts.POSTS, "posts__fk_posts_users", Posts.POSTS.AUTHOR);
        public static final ForeignKey<UsersRecord, RolesRecord> USERS__FK_USERS_ROLES = Internal.createForeignKey(com.example.stline.db.public_.Keys.ROLES_PKEY, Users.USERS, "users__fk_users_roles", Users.USERS.ROLE);
    }
}
