/*
 * This file is generated by jOOQ.
 */
package com.example.stline.db.public_;


import com.example.stline.db.public_.tables.Messages;
import com.example.stline.db.public_.tables.Photos;
import com.example.stline.db.public_.tables.Posts;
import com.example.stline.db.public_.tables.Products;
import com.example.stline.db.public_.tables.Roles;
import com.example.stline.db.public_.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.messages</code>.
     */
    public static final Messages MESSAGES = com.example.stline.db.public_.tables.Messages.MESSAGES;

    /**
     * The table <code>public.photos</code>.
     */
    public static final Photos PHOTOS = com.example.stline.db.public_.tables.Photos.PHOTOS;

    /**
     * The table <code>public.posts</code>.
     */
    public static final Posts POSTS = com.example.stline.db.public_.tables.Posts.POSTS;

    /**
     * The table <code>public.products</code>.
     */
    public static final Products PRODUCTS = com.example.stline.db.public_.tables.Products.PRODUCTS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = com.example.stline.db.public_.tables.Roles.ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = com.example.stline.db.public_.tables.Users.USERS;
}
